### ISSUE TITLE
dataset source down

### ISSUE THREAD

**Issue by horak** [aliostad/WikiRockWord2Vec#1]
The [dataset link ](https://drive.google.com/file/d/0By4PF7Jis9FzTTFpS1VVVzB4NFk/view?usp=sharing) is down unfortunately. I'm mostly just curious about how small it is and how it's formatted.

**Comment by aliostad** [comment]
Hi, sorry, yes I think I was running out of storage... I will put it back up shortly.

**Comment by horak** [comment]
Thanks!

**Comment by aliostad** [comment]
Done! Just bear in mind the link changed so please go to the readme.md again.

**Comment by horak** [comment]
Thanks so much for that @aliostad, really appreciate it :+1:

**Comment by aliostad** [comment]
no probs at all. Pleased to know this has been useful.
