### ISSUE TITLE
Having trouble training: normalisation dependency missing

### ISSUE THREAD

**Issue by horak** [aliostad/WikiRockWord2Vec#2]
When I try to train the model with:

```
$ python wiki_rock_train.py
```

I seem to be missing the `normalisation` dependency referenced in `tokenization.py`:

```
Traceback (most recent call last):
  File "wiki_rock_train.py", line 7, in <module>
    import tokenization
  File "WikiRockWord2Vec/tokenization.py", line 3, in <module>
    import normalisation
ImportError: No module named normalisation
```

Am I doing something wrong here?

**Comment by aliostad** [comment]
Hi I am sorry, it seems there is a file missing.
I will add it.

**Comment by horak** [comment]
Thanks!

**Comment by aliostad** [comment]
Sorry moved house, do not have internet at the mo... will get back to you next week.

**Comment by horak** [comment]
Priorities I can empathize with, thanks so much!

**Comment by horak** [comment]
Hey @aliostadl, just curious if you could relatively quickly add that dependency, obviously no stress if you can't!

**Comment by aliostad** [comment]
I am so sorry for the delay... I have updated the code, in fact there is no need for normaliser, it was a hangover from my other work. If you are interested in Farsi language and the normalisation of it, I can send you the code.

**Comment by horak** [comment]
Thanks, I actually just stubbed it and everything seemed to work fine so I figured that might be the case. Thanks for the offer, but I'm all set. I'll share the project I'm working on soon, I think you'll probably like it!

**Comment by aliostad** [comment]
Awesome, can't wait!
